version: '2'

services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  aerospike:
    build: ./aerospike
    ports:
      - "3000-3003:3000-3003"
    volumes:
      - aerospike-data:/opt/aerospike/data

  aerospike-amc:
    image: mrbar42/aerospike-amc
    ports:
      - "8081:8081"

  thumbor:
    image: apsl/thumbor:6.0.1
    ports:
      - "9999:8000"
    volumes:
      - thumbor-data:/data
      - thumbor-log:/logs
    environment:
      DETECTORS: "['thumbor.detectors.face_detector', 'thumbor.detectors.glasses_detector', 'thumbor.detectors.profile_detector', 'thumbor.detectors.feature_detector']"
      UPLOAD_ENABLED: 'True'
      UPLOAD_MAX_SIZE: 5242880
      UPLOAD_DELETE_ALLOWED: 'True'
      WEBP_QUALITY: 85
      ALLOW_ANIMATED_GIFS: 'False'
      RESULT_STORAGE_STORES_UNSAFE: 'True'
      RESULT_STORAGE_EXPIRATION_SECONDS: 86400

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    command: mongod --smallfiles --oplogSize 128
    volumes:
      - mongo-data:/data/configdb
      - mongo-config:/data/db

  rocketchat:
    image: rocketchat/rocket.chat:0.30.0
    ports:
      - "8080:3000"
    environment:
      MONGO_URL: "mongodb://docker_mongo_1:27017/rocketchat"
      ROOT_URL: "http://192.168.99.100:8080"
    volumes:
      - rocketchat-data:/app/uploads

  errbit:
    build: ./errbit
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URL: "mongodb://docker_mongo_1/errbit"

  mongo-express:
    image: knickers/mongo-express
    ports:
      - "5001:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "docker_mongo_1"

  cadvisor:
    image: google/cadvisor
    ports:
      - "8888:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
  aerospike-data:
    driver: local
  elasticsearch-data:
    driver: local
  thumbor-data:
    driver: local
  thumbor-log:
    driver: local
  rocketchat-data:
    driver: local
  mongo-data:
    driver: local
  mongo-config:
    driver: local
