elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

aerospike:
  build: ./aerospike
  ports:
    - "3000-3003:3000-3003"

aerospike-amc:
  build: ./aerospike-amc
  ports:
    - "8081:8081"

thumbor:
  image: apsl/thumbor:latest
  volumes:
    - data:/data
    - logs:/logs
  ports:
    - "80:80"
  environment:
    DETECTORS: "['thumbor.detectors.face_detector','thumbor.detectors.feature_detector',]"
